param(
  [string]$Pandoc = 'pandoc',
  [switch]$SkipRemoteCheck
)

$ErrorActionPreference = 'Stop'
$utf8 = [Text.UTF8Encoding]::new($false)
[Console]::OutputEncoding = $utf8
$OutputEncoding = $utf8
$openParen = [char]0xFF08
$closeParen = [char]0xFF09
$expectedUpdated = '2026-07-22T05:32:29+00:00'
$projectRoot = Split-Path -Parent $PSScriptRoot
$stylePath = Join-Path $projectRoot 'apa-7th-chinese-punctuation.csl'
$vendorPath = Join-Path (Join-Path $projectRoot 'vendor') 'apa.csl'
$metadataPath = Join-Path (Join-Path $projectRoot 'vendor') 'upstream.json'
$fixturesPath = Join-Path $PSScriptRoot 'fixtures'
$fixturePath = Join-Path $fixturesPath 'citations.md'
$bibliographyPath = Join-Path $fixturesPath 'references.bib'
$expectedCitationsPath = Join-Path $fixturesPath 'expected-citations.txt'
$filterPath = Join-Path (Join-Path $projectRoot 'filters') 'zh-citation-spacing.lua'

if (-not (Test-Path -LiteralPath $stylePath)) {
  throw "Generated style is missing: $stylePath"
}
if (-not (Test-Path -LiteralPath $vendorPath)) {
  throw "Vendored upstream style is missing: $vendorPath"
}
if (-not (Test-Path -LiteralPath $metadataPath)) {
  throw "Vendored upstream provenance is missing: $metadataPath"
}

$styleText = [IO.File]::ReadAllText($stylePath, [Text.Encoding]::UTF8)
[xml]$style = $styleText
$ns = [Xml.XmlNamespaceManager]::new($style.NameTable)
$ns.AddNamespace('csl', 'http://purl.org/net/xbiblio/csl')

$layout = $style.SelectSingleNode('/csl:style/csl:citation/csl:layout', $ns)
if ($null -eq $layout) {
  throw 'Citation layout is missing.'
}
if ($layout.GetAttribute('prefix') -ne $openParen -or
    $layout.GetAttribute('suffix') -ne $closeParen -or
    $layout.GetAttribute('delimiter') -ne '; ') {
  throw 'Citation layout does not use full-width outer parentheses with the APA delimiter.'
}
$citationGroup = $layout.SelectSingleNode('./csl:group[1]', $ns)
if ($citationGroup.GetAttribute('delimiter') -ne ', ') {
  throw 'Citation author/date/locator delimiter differs from APA.'
}

$title = $style.SelectSingleNode('/csl:style/csl:info/csl:title', $ns).InnerText
$id = $style.SelectSingleNode('/csl:style/csl:info/csl:id', $ns).InnerText
$license = $style.SelectSingleNode('/csl:style/csl:info/csl:rights', $ns).GetAttribute('license')
$updated = $style.SelectSingleNode('/csl:style/csl:info/csl:updated', $ns).InnerText
if ($title -ne 'APA 7th edition (Chinese full-width parentheses)') { throw 'Unexpected style title.' }
if ($id -ne 'https://github.com/qrkks/apa-7th-chinese-punctuation-csl') { throw 'Unexpected style ID.' }
if ($license -ne 'http://creativecommons.org/licenses/by-sa/3.0/') { throw 'Upstream CC BY-SA license was not preserved.' }
if ($updated -ne $expectedUpdated) { throw 'Unexpected style updated timestamp.' }
if ($styleText.Contains('Style Variant Builder') -or
    -not $styleText.Contains('Generated by scripts/build-style.ps1; do not edit this file directly.')) {
  throw 'Generated-file notice does not point contributors to the local build script.'
}

$vendorText = [IO.File]::ReadAllText($vendorPath, [Text.Encoding]::UTF8)
[xml]$upstream = $vendorText
$upstreamNs = [Xml.XmlNamespaceManager]::new($upstream.NameTable)
$upstreamNs.AddNamespace('csl', 'http://purl.org/net/xbiblio/csl')
$bibliography = $style.SelectSingleNode('/csl:style/csl:bibliography', $ns)
$upstreamBibliography = $upstream.SelectSingleNode('/csl:style/csl:bibliography', $upstreamNs)
if ($bibliography.OuterXml -ne $upstreamBibliography.OuterXml) {
  throw 'Bibliography section differs from the vendored APA CSL.'
}

$provenance = Get-Content -Raw -Encoding UTF8 $metadataPath | ConvertFrom-Json
if ($provenance.repository -ne 'citation-style-language/styles' -or
    $provenance.version_branch -ne 'v1.0.2' -or
    $provenance.path -ne 'apa.csl' -or
    $provenance.commit -notmatch '^[0-9a-f]{40}$' -or
    $provenance.sha256 -notmatch '^[0-9a-f]{64}$') {
  throw 'Vendored upstream provenance is invalid.'
}
$vendorSha256 = (Get-FileHash -LiteralPath $vendorPath -Algorithm SHA256).Hash.ToLowerInvariant()
if ($vendorSha256 -ne $provenance.sha256) {
  throw 'Vendored APA CSL does not match its recorded SHA-256 hash.'
}

if (-not $SkipRemoteCheck) {
  $upstreamUrl = "https://raw.githubusercontent.com/$($provenance.repository)/$($provenance.commit)/$($provenance.path)"
  $remoteText = (Invoke-WebRequest -Uri $upstreamUrl -UseBasicParsing).Content
  if (($vendorText -replace "`r`n", "`n") -ne ($remoteText -replace "`r`n", "`n")) {
    throw 'Vendored APA CSL differs from its pinned official upstream commit.'
  }
}

$rendered = & $Pandoc $fixturePath --citeproc `
  "--bibliography=$bibliographyPath" "--csl=$stylePath" `
  "--lua-filter=$filterPath" -t plain
if ($LASTEXITCODE -ne 0) {
  throw "Pandoc smoke test failed with exit code $LASTEXITCODE."
}
$renderedText = $rendered -join "`n"

$expected = [IO.File]::ReadAllLines($expectedCitationsPath, $utf8)
foreach ($value in $expected) {
  if (-not $renderedText.Contains($value)) {
    throw "Pandoc output is missing expected citation: $value`n$renderedText"
  }
}

Write-Output 'All CSL tests passed.'
